services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-next_recipe_hub}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
